config/routes.rb
require 'sidekiq/web'

SidekiqSnippet::Application.routes.draw do
  resources :snippets
  root to: "snippets#new"
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :language, :plain_code, :highlighted_code

  validates :language, :inclusion => { :in => %w[ruby python javascript css] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def show
    @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      PygmentsWorker.perform_async(@snippet.id)
      redirect_to @snippet
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidekiqSnippet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= form_for @snippet do |f| %>
  <% if @snippet.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibted this snippet from being saved:</h2>
      <ul>
        <% @snippet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, options_for_select([["Ruby", "ruby"], ["Python", "python"], ["JavaScript", "javascript"], ["CSS", "css"]]) %>
  </div>
  <div class ="field">
    <%= f.label :plain_code, "Source code" %><br />
    <%= f.text_area :plain_code, rows: 14, cols: 50 %>
  </div>
  <div class="actions"><%= f.submit "Post Snippet" %></div>
<% end %>

app/views/snippets/show.html.erb
<h1>Snippet</h1>

<p>
  <b>Language:</b>
  <%= @snippet.language.titleize %>
</p>
<div class="code_block">
  <% if @snippet.highlighted_code.present? %>
    <%= raw @snippet.highlighted_code %>
  <% else %>
    <pre><%= @snippet.plain_code %></pre>
  <% end %>
</div>

<p>
  <%= link_to "New Snippet", new_snippet_path %>
</p>